Jewellery/Areas/Admin2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Domains;
using Jewellery.BL;
using Jewellery.InfraStructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Jewellery.Areas.Admin2.Controllers
{
    [Area("Admin2")]
    public class HomeController : Controller
    {
        JewelContext ctx;
        IProductService IProduct;
        public HomeController(JewelContext context,IProductService product)
        {
            ctx = context;
            IProduct = product;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Slider()
        {
            return View(IProduct._slider());
        }

        public IActionResult EditSlider(int? id)
        {
            
            if (id != null)
            {


                return View(IProduct.GetSliderById(Convert.ToInt32(id)));
            }
            else
            {
                return View();
            }

        }
        [HttpPost]
        public async Task<IActionResult> SaveSlider(TbSlider slider, List<IFormFile> Files)
        {

            foreach (var file in Files)
            {
                if (file.Length > 0)
                {
                    string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Slider", ImageName);
                    using (var stream = System.IO.File.Create(filePaths))
                    {
                        await file.CopyToAsync(stream);
                    }
                    slider.SliderImage = ImageName;
                }
            }

            if (slider.TbSliderId == 0)
            {
                IProduct.addslider(slider);

            }
            else
            {
                IProduct.editslider(slider);
            }
            return RedirectToAction("Slider");

        }
        public IActionResult Delete(int id)
        {
            IProduct.DeleteSlider(id);
            return RedirectToAction("Slider");
        }



    }
}

Jewellery/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domains;
using Jewellery.BL;
using Jewellery.InfraStructure;
using Jewellery.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;

namespace Jewellery.Controllers
{
    public class DetailsController : Controller
    {
        JewelContext ctx;
        IProductService IProduct;
        public DetailsController(JewelContext context,IProductService x)
        {
            ctx = context;
            IProduct = x;
        }
        public IActionResult Index(int id)
        {
            DetailsViewModel model = new DetailsViewModel();
            model.Product = IProduct.ProductWithImage(id);
            model.ListRelated = IProduct.Related(model.Product.ProductPrice).ToList();
            return View(model);
        }


        
//          div.ajaxbg {
//    background: rgba(255,255,255, .8);
//    position: absolute;
//    top: 0;
//    left: 0;
//    width: 100%;
//    height: 100%;
//    transition-duration: 10s;
//    z-index: 1;
//}

//    div.ajaxbg > img {
//        position: absolute;
//        top: 30%;
//        left: 50%;
       
//         transform: translateX(-50%);
//        z-index: 2;
//    }

//div.ajaxbg > p {
//        position: absolute;
//        top: 50px;
//        z-index: 2;
//    }

        
        

    }
}

Jewellery/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Domains;
using Jewellery.BL;
using Jewellery.InfraStructure;
using Jewellery.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Jewellery.Controllers
{
   


public class HomeController : Controller
    {
       
        IProductService IProduct;
        JewelContext ctx;
        public HomeController(IProductService csa, JewelContext context)
        {
            
            IProduct = csa;
            ctx = context;
        }

        public IActionResult Index()
        {
            HomePageViewModel _model = new HomePageViewModel();
            _model.ListSlider = IProduct._slider().ToList();
            _model.ListAllProducts = IProduct.GetAll();
            _model.ListNewProducts = _model.ListAllProducts.Skip(25).Take(8).ToList();
            _model.Instagram = _model.ListAllProducts.Skip(35).Take(10).ToList();
            _model.ListBestSeller = _model.ListAllProducts.Skip(16).Take(8).ToList();
            _model.ListFeatureProducts = _model.ListAllProducts.Take(8).ToList();
            
           //begin count
          
            ViewBag.Rings = (int)Math.Ceiling((decimal)ctx.TbProduct.Where(a => a.CategoryId == 1).Count());
            ViewBag.Diamonds = (int)Math.Ceiling((decimal)ctx.TbProduct.Where(a => a.CategoryId == 2).Count());
            ViewBag.Necklace = (int)Math.Ceiling((decimal)ctx.TbProduct.Where(a => a.CategoryId == 3).Count());
            ViewBag.Watches = (int)Math.Ceiling((decimal)ctx.TbProduct.Where(a => a.CategoryId == 4).Count());
            ViewBag.Tiara = (int)Math.Ceiling((decimal)ctx.TbProduct.Where(a => a.CategoryId == 5).Count());
            ViewBag.Earrings = (int)Math.Ceiling((decimal)ctx.TbProduct.Where(a => a.CategoryId == 6).Count());
           //end count
            

            return View(_model);
            // _model.ListCategory = _model.ListAllProducts.GroupBy(a => a.CategoryId).Select(a => a.First()).ToList();

        }
       
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append
                (
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
                );

            return LocalRedirect(returnUrl);
        }

        public async Task<IActionResult> ProductsByCategory(string categorySlug, int page = 1)
        {
            TbCategory category = await ctx.TbCategory.Where(x => x.Slug == categorySlug).FirstOrDefaultAsync();
            if (category == null) return RedirectToAction("Index");

            int pageSize = 8;
            var products = ctx.TbProduct.Where(x => x.CategoryId == category.TbCategoryId).Skip((page - 1) * pageSize).Take(pageSize);

            ViewBag.PageNumber = page;
            ViewBag.PageRange = pageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((decimal)ctx.TbProduct.Where(x => x.CategoryId == category.TbCategoryId).Count() / pageSize);
            ViewBag.CategoryName = category.CategoryName;
            ViewBag.CategorySlug = categorySlug;

            return View(await products.ToListAsync());
        }
        public IActionResult All()
        {

            return View();
        }

       

    }
}

Jewellery/Controllers/WishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Jewellery.Models;
using Jewellery.BL;
using Domains;
using Jewellery.InfraStructure;

namespace MultiKartt.Controllers
{
    public class WishListController : Controller
    {
        IProductService IProduct;
        public WishListController(IProductService service)
        {
            IProduct = service;
        }
        public IActionResult AddToWishList(int id)
        {
            WishListModel wishes = HttpContext.Session.GetObjectFromJson<WishListModel>("wishlist");
            if (wishes == null)
            {
                wishes = new WishListModel();


            }
            TbProduct product = IProduct.GetById(id);

            wishes.ListWish.Add(new WishListData()
            {
                WishListDataId = product.TbProductId,
                ProductName = product.ProductName,
                Image = product.ProductImageName,
                Price = product.ProductPrice
            });

            HttpContext.Session.SetObjectAsJson("wishlist", wishes);
            return Redirect("/WishList/wishlist");
        }
        public IActionResult wishlist()
        {
            WishListModel wishes = HttpContext.Session.GetObjectFromJson<WishListModel>("wishlist") ?? new WishListModel();
            return View(wishes);
        }
       
            public IActionResult RemoveItem(int id)
        {
            WishListModel oShopingCart = HttpContext.Session.GetObjectFromJson<WishListModel>("wishlist");
            oShopingCart.ListWish.Remove(oShopingCart.ListWish.Where(a => a.WishListDataId == id).FirstOrDefault());
            HttpContext.Session.SetObjectAsJson("wishlist", oShopingCart);
            return RedirectToAction("wishlist");
        }
    }
}

Jewellery/Views/Home/All.cshtml
<br />
<br />
<br />
<body>
    <!-- section start -->
    <section class="section-b-space ratio_asos">
        <div class="collection-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3 collection-filter">
                        <!-- side-bar colleps block stat -->
                        <div class="collection-filter-block">
                            <!-- brand filter start -->
                            <div class="collection-mobile-back">
                                <span class="filter-back">
                                    <i class="fa fa-angle-left"
                                       aria-hidden="true"></i> back
                                </span>
                            </div>
                            <div class="collection-collapse-block open">
                                <h3 class="collapse-block-title">Categories</h3>
                                <div class="collection-collapse-block-content">

                                    <div class="collection-brand-filter" id="Categories">
                                        @*<div class="col-md-3" >
                                                <a class="btn btn-solid" href="/Home/Index">Necklace</a>
                                            </div>
                                            <br />*@

                                    </div>
                                </div>
                            </div>


                        </div>
                        <!-- silde-bar colleps block end here -->


                    </div>


                    <div class="collection-content col">
                        <div class="page-main-content">
                            <div class="row">
                                <div class="col-sm-12">

                                    <div class="collection-product-wrapper">

                                        <div class="product-wrapper-grid">
                                            <div class="row margin-res" id="DivTemplate1">

                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- section End -->

</body>
@section Scripts
{
    <script src="~/Modules/Helper.js"></script>
    <script src="~/Modules/JsProduct.js"></script>
    <script src="~/Modules/JsCategory.js"></script>
}

Jewellery/Views/Home/ProductsByCategory.cshtml
@model List<TbProduct>
<!DOCTYPE html>
<html lang="en"

<body>

    <!-- section start -->
    <section class="section-b-space ratio_asos">
        <div class="collection-wrapper">
            <div class="container">
                <div class="row">
                    <div class="collection-content col">
                        <div class="page-main-content">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="top-banner-wrapper">
                                        <a href="#"><img src="/Slider/5.jpg" class="img-fluid blur-up lazyload" alt=""></a>

                                    </div>
                                    <div class="collection-product-wrapper">

                                        <div class="product-wrapper-grid">
                                            <div class="row margin-res">
                                                @foreach (var item in Model)
                                                {
                                                    <div class="col-xl-3 col-6 col-grid-box">

                                                        <div class="product-box">
                                                            <div class="img-wrapper">
                                                                <div class="ajaxbg d-none">
                                                                    <img src="~/assets/images/ajax-loader.gif" />
                                                                    <p  class="lead alert alert-info     text-center d-none">
                                                                       Successfully added To Cart!
                                                                    </p>
                                                                </div>
                                                                
                                                                <div class="front">
                                                                    <a asp-controller="Details" asp-action="Index" asp-route-id="@item.TbProductId"><img src="@string.Format("/Uploads/{0}", item.ProductImageName)" class="img-fluid blur-up lazyload bg-img" alt=""></a>
                                                                </div>

                                                                <div class="cart-info cart-wrap">
                                                                    <a data-target="#addtocart"
                                                                       title="Add to cart" asp-controller="Cart" asp-action="AddToCart" asp-route-id="@item.TbProductId"
                                                                       data-id="@item.TbProductId" class="AddToCart">
                                                                        <i class="ti-shopping-cart "></i>
                                                                    </a>


                                                                    <a asp-controller="WishList" asp-action="AddToWishList" asp-route-id="@item.TbProductId"
                                                                       data-id="@item.TbProductId" class="AddTowishlist" title="Add to Wishlist">
                                                                        <i class="ti-heart" aria-hidden="true"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <div class="product-detail">
                                                                <div>
                                                                    <div class="rating"><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i></div>
                                                                    <a asp-controller="Details" asp-action="Index" asp-route-id="@item.TbProductId">
                                                                        <h6>@item.ProductName</h6>
                                                                    </a>

                                                                    <h4>$@item.ProductPrice</h4>

                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>
                                                }
                                              
                                                @if (ViewBag.TotalPages > 1)
                                                {
                                                    <div class="d-flex w-100 justify-content-center">
                                                        <pagination page-count="@ViewBag.TotalPages" page-target="/Home/@ViewBag.CategorySlug" page-number="@ViewBag.PageNumber" page-range="@ViewBag.PageRange"></pagination>
                                                    </div>
                                                }
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- section End -->

</body>

</html>
@section Scripts
 {

    <script>
        $(function () {

            $("a.AddToCart").click(function (e) {
                e.preventDefault();

                let ajaxDiv = $(this).parent().parent().find("div.ajaxbg");
                ajaxDiv.removeClass("d-none");
                let id = $(this).data("id");

                $.get('/Cart/AddToCart/' + id, {}, function (data) {
                    $("ul.show-div").html(data);
                    ajaxDiv.find("img").addClass("d-none");
                    ajaxDiv.find("img").addClass("d-none");
                    ajaxDiv.find("p").removeClass("d-none");
                    setTimeout(() => {
                        ajaxDiv.animate({ opacity: 0 }, function () {
                            $(this).addClass("d-none").fadeTo(.1, 1);
                            $(this).find("img").removeClass("d-none");
                            $(this).find("p").addClass("d-none");
                        });
                    });
                });
            });
            

        });

        $(function () {

            $("a.AddTowishlist").click(function (e) {
                e.preventDefault();

                let ajaxDiv = $(this).parent().parent().find("div.ajaxbg");
                ajaxDiv.removeClass("d-none");
                let id = $(this).data("id");

                $.get('/WishList/AddToWishList/' + id, {}, function (data) {
                    $("li.show-div").html(data);
                    
                    setTimeout(() => {
                        ajaxDiv.animate({ opacity: 0 }, function () {
                            $(this).addClass("d-none").fadeTo(.1, 1);
                            
                            $(this).find("img").removeClass("d-none");
                         
                            $(this).find("p").addClass("d-none");
                        });
                    });
                });
            });


        });
    </script>
}